### ISSUE TITLE
aspectjweaver missing dependency?

### ISSUE THREAD

**Issue by davidstrauss** [hmsonline/virgil#18]
[root@david-edge virgil]# mvn package
< omitted, but successful >
[root@david-edge virgil]# assembly/bin/virgil
Error opening zip file or JAR manifest missing : assembly/bin/../lib/aspectjweaver-1.6.11.jar
Error occurred during initialization of VM
agent library failed to init: instrument

Am I initializing this incorrectly? Or is this just a dependency you have on your build systems that Maven isn't pulling (but should)?

**Comment by boneill42** [comment]
David,

Here is what works for me:
(I just verified against latest in github)

gitbone@zen:~/dev/hmsonline-> git clone git@github.com:hmsonline/virgil.git

bone@zen:~/dev/hmsonline-> cd virgil/
bone@zen:~/dev/hmsonline/virgil-> mvn clean install

bone@zen:~/dev/hmsonline/virgil-> mvn assembly:assembly

bone@zen:~/dev/hmsonline/virgil-> cd target/
bone@zen:~/dev/hmsonline/virgil/target-> unzip
virgil-0.15.2-SNAPSHOT-bin.zip

...
bone@zen:~/dev/hmsonline/virgil/target-> cd virgil-0.15.2-SNAPSHOT
bone@zen:~/dev/hmsonline/virgil/target/virgil-0.15.2-SNAPSHOT-> bin/virgil
-host localhost

Then just hit:
http://localhost:8080

I use this when testing builds.
When developing, I just run inside eclipse.
I'll post this to the wiki.

-brian

## 

Brian O'Neill
Lead Architect, Software Development
Health Market Science | 2700 Horizon Drive | King of Prussia, PA 19406
p: 215.588.6024
www.healthmarketscience.com

On 4/23/12 6:06 AM, "David Strauss"
<reply+i-4237559-ed96dbbd23f4b6eb5508e4ae9c2ff68fcbfee00b-897229@reply.gith
ub.com> wrote:

**Comment by boneill42** [comment]
https://github.com/hmsonline/virgil/wiki/building-from-scratch

Closing the issue for now.  Please re-open if those instructions don't work for you.

**Comment by shhrohan** [comment]
My cassandra setup is running on `PasswordAuthenticator` mode. Please tell me where i can add username and password values to start virgil server.
